import { CrawlerRequestResponse } from "crawler";
import { Result } from "htmlmetaparser";
type Product = any;

const naiveKeywordLookup: {[word: string]: string} = {
    course: 'education',
    case: 'accessories',
    system: 'technology',
    party: 'novelty',
    parties: 'novelty',
    information: 'technology',
    informations: 'technology',
    home: 'household',
    power: 'technology',
    room: 'household',
    court: 'sport',
    car: 'automotive',
    road: 'automotive',
    face: 'wellness',
    education: 'education',
    office: 'stationary',
    body: 'wellness',
    bodies: 'wellness',
    health: 'wellness',
    healths: 'wellness',
    mother: 'gift',
    period: 'wellness',
    book: 'stationary',
    age: 'wellness',
    support: 'wellness',
    care: 'wellness',
    study: 'education',
    studies: 'education',
    food: 'grocery',
    foods: 'grocery',
    language: 'education',
    paper: 'stationary',
    university: 'education',
    universities: 'education',
    computer: 'technology',
    hair: 'wellness',
    growth: 'wellness',
    relationship: 'wellness',
    treatment: 'wellness',
    energies: 'wellness',
    technology: 'technology',
    technologies: 'technology',
    garden: 'household',
    style: 'fashion',
    fish: 'grocery',
    oil: 'wellness',
    television: 'technology',
    blood: 'wellness',
    software: 'technology',
    radio: 'technology',
    baby: 'wellness',
    babies: 'wellness',
    machine: 'technology',
    sex: 'wellness',
    tea: 'grocery',
    dog: 'pet',
    cat: 'pet',
    hamster: 'pet',
    horse: 'pet',
    stock: 'grocery',
    kitchen: 'household',
    plant: 'household',
    bar: 'grocery',
    foot: 'wellness',
    feet: 'wellness',
    pain: 'wellness',
    farm: 'grocery',
    video: 'technology',
    videos: 'technology',
    tv: 'technology',
    tvs: 'technology',
    telephone: 'technology',
    coffee: 'grocery',
    phone: 'technology',
    exercise: 'wellness',
    wine: 'grocery',
    china: 'household',
    neck: 'wellness',
    drug: 'wellness',
    lunch: 'grocery',
    lunches: 'grocery',
    brain: 'wellness',
    drink: 'grocery',
    sport: 'wellness',
    fashion: 'fashion',
    vehicle: 'automotive',
    van: 'automotive',
    meal: 'grocery',
    breakfast: 'grocery',
    motor: 'automotive',
    beauty: 'wellness',
    beauties: 'wellness',
    vision: 'wellness',
    fuel: 'automotive',
    bedroom: 'household',
    fruit: 'grocery',
    bottle: 'grocery',
    dress: 'fashion',
    dresses: 'fashion',
    bath: 'household',
    sugar: 'grocery',
    bread: 'grocery',
    meat: 'grocery',
    restaurant: 'grocery',
    sweet: 'grocery',
    savoury: 'grocery',
    chocolate: 'grocery',
    cocktail: 'grocery',
    sausage: 'grocery',
    burger: 'grocery',
    bun: 'grocery',
    snack: 'grocery',
    mouthful: 'grocery',
    mouthfuls: 'grocery',
    milk: 'grocery',
    nut: 'grocery',
    protein: 'grocery',
    saturates: 'grocery',
    saturated: 'grocery',
    golf: 'wellness',
}

export default (result: Result, res: CrawlerRequestResponse, product: Product) => {
    if (product.category) return {};
    const searchDomain = product.name + ' ' + product.description;
    return {
        category: searchDomain.toLocaleLowerCase()
            .replace(/[^\s\w\d]+/ig, '')
            .split(/[\s\b]+/)
            .map((word) => {
                return naiveKeywordLookup[word]
            })
            .filter((a) => !!a)
            .filter((v, i, a) => a.indexOf(v) === i)
    }
}